import { Router } from 'express'
import { z } from 'zod'
import multer from 'multer'
import { analyseCv } from '../services/cvAnalysis.js'
import { requireAuth } from '../middleware/auth.js'
import { supabase } from '../lib.js'

const uploadCv = multer({ storage: multer.memoryStorage(), limits: { fileSize: 10 * 1024 * 1024 } })

const updateMeSchema = z.object({
  fullName: z.string().min(2).optional(),
  bio: z.string().max(500).optional().nullable(),
  headline: z.string().max(120).optional().nullable(),
  university: z.string().optional(),
  currentCompany: z.string().optional(),
  avatarUrl: z
    .string()
    .max(180000)
    .refine((value) => value.startsWith('http://') || value.startsWith('https://') || value.startsWith('data:image/'), {
      message: 'avatarUrl must be a URL or image data URL',
    })
    .nullable()
    .optional(),
  bannerUrl: z
    .string()
    .max(1400000)
    .refine((value) => value.startsWith('http://') || value.startsWith('https://') || value.startsWith('data:image/'), {
      message: 'bannerUrl must be a URL or image data URL',
    })
    .nullable()
    .optional(),
  profileLayout: z
    .array(z.object({ id: z.string().max(40), visible: z.boolean() }))
    .max(40)
    .nullable()
    .optional(),
  locationCity: z.string().optional(),
  status: z.enum(['studying', 'open_to_work', 'employed']).optional(),
  locationLat: z.number().optional(),
  locationLng: z.number().optional(),
  websiteUrl: z.string().max(200).optional().nullable(),
  githubUrl: z.string().max(200).optional().nullable(),
  linkedinUrl: z.string().max(200).optional().nullable(),
  languages: z.array(z.string().max(50)).optional(),
  openToRoles: z.boolean().optional(),
  asksPerMonth: z.number().int().min(0).max(30).optional().nullable(),
  canHelpWith: z.string().max(300).optional().nullable(),
  // Connective layer
  persona: z.enum(['student', 'professional', 'professor', 'investor']).optional().nullable(),
  interests: z.array(z.string().max(60)).max(20).optional(),
  goals: z.array(z.string().max(60)).max(20).optional(),
  isInternational: z.boolean().optional().nullable(),
  homeCountry: z.string().max(80).optional().nullable(),
  munichTenure: z.string().max(40).optional().nullable(),
  socialEnergy: z.enum(['active', 'selective', 'gentle']).optional().nullable(),
  tourCompletedAt: z.string().datetime().optional().nullable(),
})

const searchUsersQuerySchema = z.object({
  q: z.string().trim().max(80).default(''),
  skill: z.string().trim().max(60).default(''),
})

const userPanelParamSchema = z.object({
  id: z.string().uuid(),
})

const usernameParamSchema = z.object({
  username: z.string().min(3).max(32).regex(/^[a-zA-Z0-9_]+$/),
})

export const usersRouter = Router()

usersRouter.get('/me', requireAuth, async (req, res) => {
  if (!req.authUser) {
    return res.status(401).json({ error: 'Unauthorized' })
  }

  let row = (await supabase.from('users').select('*').eq('auth_id', req.authUser.id).maybeSingle()).data

  // Self-heal: auto-create the profile row if missing (recovers from failed signup completions)
  if (!row) {
    const email = req.authUser.email ?? `user-${req.authUser.id.slice(0, 8)}@unknown.app`
    const baseUsername = `user_${req.authUser.id.replace(/-/g, '').slice(0, 12)}`
    const stem = (email.split('@')[0] ?? 'New user').replace(/[._-]+/g, ' ')
    const fullName = stem.charAt(0).toUpperCase() + stem.slice(1)

    // Auto-promote knotify team emails to admin on first profile creation
    const ADMIN_EMAILS = ['armen.ter-minasyan@tum.de', 'jaydip.gohil@tum.de']
    const isAdmin = ADMIN_EMAILS.includes(email.toLowerCase())

    const insert = await supabase
      .from('users')
      .insert({
        auth_id: req.authUser.id,
        email,
        username: baseUsername,
        full_name: fullName,
        location_city: 'Munich',
        status: 'open_to_work',
        is_admin: isAdmin,
      })
      .select('*')
      .single()

    if (insert.error) {
      console.error('[users/me] auto-create failed:', insert.error)
      return res.status(500).json({ error: insert.error.message })
    }
    row = insert.data
  } else {
    // Backfill admin flag if the team signed up before the seeding migration ran
    const ADMIN_EMAILS = ['armen.ter-minasyan@tum.de', 'jaydip.gohil@tum.de']
    if (!row.is_admin && row.email && ADMIN_EMAILS.includes(row.email.toLowerCase())) {
      const upd = await supabase.from('users').update({ is_admin: true }).eq('id', row.id).select('*').single()
      if (!upd.error && upd.data) row = upd.data
    }
  }

  return res.json({ user: row })
})

function profileText(value: unknown) {
  return typeof value === 'string' && value.trim().length > 0
}

function isAutoGeneratedUsername(username: unknown) {
  return typeof username === 'string' && /^user_[a-z0-9]{12}$/i.test(username)
}

function getOnboardingMissingFields(user: Record<string, unknown>) {
  const missing: string[] = []
  const interests = Array.isArray(user.interests) ? user.interests : []
  const goals = Array.isArray(user.goals) ? user.goals : []

  if (!profileText(user.full_name)) missing.push('fullName')
  if (!profileText(user.persona)) missing.push('persona')
  if (interests.length < 3) missing.push('interests')
  if (goals.length < 1) missing.push('goals')

  return missing
}

usersRouter.get('/me/onboarding-status', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })

  const userResult = await supabase
    .from('users')
    .select('id, full_name, username, persona, interests, goals, location_city, tour_completed_at')
    .eq('id', req.appUserId)
    .maybeSingle()

  if (userResult.error) return res.status(500).json({ error: userResult.error.message })
  if (!userResult.data) return res.status(404).json({ error: 'Profile not found' })

  const skillsResult = await supabase
    .from('user_skills')
    .select('skill_id', { count: 'exact', head: true })
    .eq('user_id', req.appUserId)

  const skillsCount = skillsResult.count ?? 0
  const missing = getOnboardingMissingFields(userResult.data)

  return res.json({
    complete: missing.length === 0,
    missing,
    skillsCount,
    minSkills: 3,
    tourCompleted: Boolean(userResult.data.tour_completed_at),
  })
})
usersRouter.patch('/me', requireAuth, async (req, res) => {
  if (!req.authUser) {
    return res.status(401).json({ error: 'Unauthorized' })
  }

  const parsed = updateMeSchema.safeParse(req.body)
  if (!parsed.success) {
    return res.status(422).json({ error: 'Invalid payload', fields: parsed.error.flatten() })
  }

  const data = parsed.data
  const update: Record<string, unknown> = {}
  if (data.fullName !== undefined) update.full_name = data.fullName.trim()
  if (data.bio !== undefined) update.bio = data.bio ? data.bio.trim() : null
  if (data.university !== undefined) update.university = data.university.trim()
  if (data.currentCompany !== undefined) update.current_company = data.currentCompany.trim()
  if (data.avatarUrl !== undefined) update.avatar_url = data.avatarUrl ? data.avatarUrl.trim() : null
  if (data.bannerUrl !== undefined) update.banner_url = data.bannerUrl ? data.bannerUrl.trim() : null
  if (data.profileLayout !== undefined) update.profile_layout = data.profileLayout
  if (data.locationCity !== undefined) update.location_city = data.locationCity.trim()
  if (data.status !== undefined) update.status = data.status
  if (data.locationLat !== undefined) update.location_lat = data.locationLat
  if (data.locationLng !== undefined) update.location_lng = data.locationLng
  if (data.headline !== undefined) update.headline = data.headline
  if (data.websiteUrl !== undefined) update.website_url = data.websiteUrl
  if (data.githubUrl !== undefined) update.github_url = data.githubUrl
  if (data.linkedinUrl !== undefined) update.linkedin_url = data.linkedinUrl
  if (data.languages !== undefined) update.languages = data.languages
  if (data.openToRoles !== undefined) update.open_to_roles = data.openToRoles
  if (data.asksPerMonth !== undefined) update.asks_per_month = data.asksPerMonth
  if (data.canHelpWith !== undefined) update.can_help_with = data.canHelpWith
  if (data.persona !== undefined) update.persona = data.persona
  if (data.interests !== undefined) update.interests = data.interests
  if (data.goals !== undefined) update.goals = data.goals
  if (data.isInternational !== undefined) update.is_international = data.isInternational
  if (data.homeCountry !== undefined) update.home_country = data.homeCountry ? data.homeCountry.trim() : null
  if (data.munichTenure !== undefined) update.munich_tenure = data.munichTenure
  if (data.socialEnergy !== undefined) update.social_energy = data.socialEnergy
  if (data.tourCompletedAt !== undefined) update.tour_completed_at = data.tourCompletedAt

  if (Object.keys(update).length === 0) {
    return res.status(400).json({ error: 'No fields provided' })
  }
  update.updated_at = new Date().toISOString()

  const result = await supabase.from('users').update(update).eq('auth_id', req.authUser.id).select('*').single()
  if (result.error) {
    return res.status(500).json({ error: result.error.message })
  }

  return res.json({ user: result.data })
})

// Role requests (member asking to be HR / company_owner)
const roleRequestSchema = z.object({
  requestedRole: z.enum(['hr', 'company_owner']),
  companyName: z.string().min(2).max(120).optional(),
})

usersRouter.post('/me/role-requests', requireAuth, async (req, res) => {
  if (!req.appUserId || !req.authUser) return res.status(401).json({ error: 'Unauthorized' })
  const parsed = roleRequestSchema.safeParse(req.body)
  if (!parsed.success) return res.status(422).json({ error: 'Invalid payload', fields: parsed.error.flatten() })

  // Reject if there's already a pending request for the same role
  const existing = await supabase
    .from('role_requests')
    .select('id')
    .eq('user_id', req.appUserId)
    .eq('requested_role', parsed.data.requestedRole)
    .eq('status', 'pending')
    .maybeSingle()
  if (existing.error) return res.status(500).json({ error: existing.error.message })
  if (existing.data) return res.status(409).json({ error: 'You already have a pending request for this role' })

  const email = req.authUser.email ?? ''
  const domain = email.includes('@') ? email.split('@')[1].toLowerCase() : null
  // Naive heuristic: an "@company.com" email matching the company name is auto-trusted (still admin-reviewed)
  const emailVerified = Boolean(
    domain && parsed.data.companyName && domain.replace(/\.[a-z]+$/, '').includes(parsed.data.companyName.toLowerCase().replace(/\s+/g, ''))
  )

  const insert = await supabase
    .from('role_requests')
    .insert({
      user_id: req.appUserId,
      requested_role: parsed.data.requestedRole,
      company_name: parsed.data.companyName ?? null,
      email_domain: domain,
      email_verified: emailVerified,
    })
    .select('*')
    .single()
  if (insert.error) return res.status(500).json({ error: insert.error.message })
  return res.status(201).json({ request: insert.data })
})

usersRouter.get('/me/role-requests', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(401).json({ error: 'Unauthorized' })
  const result = await supabase
    .from('role_requests')
    .select('*')
    .eq('user_id', req.appUserId)
    .order('created_at', { ascending: false })
  if (result.error) return res.status(500).json({ error: result.error.message })
  return res.json({ requests: result.data ?? [] })
})

type DiscoverSkill = {
  skill_id: number
  name: string
  category: string | null
}

function normaliseDiscoverText(value: unknown) {
  return typeof value === 'string' ? value.trim().toLowerCase() : ''
}

async function skillsForUsers(userIds: string[]) {
  const byUser = new Map<string, DiscoverSkill[]>()
  if (userIds.length === 0) return byUser

  const result = await supabase
    .from('user_skills')
    .select('user_id, skill_id, skill_catalog(id, name, category)')
    .in('user_id', userIds)

  if (result.error) throw new Error(result.error.message)

  for (const row of result.data ?? []) {
    const catalog = Array.isArray((row as any).skill_catalog)
      ? (row as any).skill_catalog[0]
      : (row as any).skill_catalog

    if (!catalog?.name) continue

    const list = byUser.get((row as any).user_id) ?? []
    list.push({
      skill_id: Number((row as any).skill_id),
      name: String(catalog.name),
      category: catalog.category ? String(catalog.category) : null,
    })
    byUser.set((row as any).user_id, list)
  }

  return byUser
}

function discoverProfileSignal(user: any, skills: DiscoverSkill[]) {
  let score = 0

  if (profileText(user?.full_name)) score += 15
  if (profileText(user?.headline)) score += 20
  if (profileText(user?.location_city)) score += 15
  if (profileText(user?.status)) score += 10
  if (profileText(user?.university) || profileText(user?.current_company)) score += 15
  if (profileText(user?.bio)) score += 10

  score += Math.min(skills.length, 5) * 6

  return Math.min(score, 100)
}

// ── Connective-layer matching helpers ──────────────────────────────────────
function lcSet(arr: unknown): Set<string> {
  if (!Array.isArray(arr)) return new Set()
  return new Set(arr.filter((x): x is string => typeof x === 'string').map((x) => x.trim().toLowerCase()))
}

// Returns the original-cased labels from `theirs` that also appear in `mine`.
function overlapLabels(mine: Set<string>, theirs: unknown): string[] {
  if (!Array.isArray(theirs)) return []
  const out: string[] = []
  for (const v of theirs) {
    if (typeof v === 'string' && mine.has(v.trim().toLowerCase())) out.push(v)
  }
  return out
}

function discoverReasonFor(me: any, mySkills: DiscoverSkill[], candidate: any, candidateSkills: DiscoverSkill[], mutualCount = 0) {
  const mySkillNames = new Set(mySkills.map((s) => normaliseDiscoverText(s.name)).filter(Boolean))
  const sharedSkills = candidateSkills
    .filter((s) => mySkillNames.has(normaliseDiscoverText(s.name)))
    .map((s) => s.name)

  // Connective layer: interests, goals, languages
  const myInterests = lcSet(me?.interests)
  const sharedInterests = overlapLabels(myInterests, candidate?.interests)
  const myGoals = lcSet(me?.goals)
  const candGoals = lcSet(candidate?.goals)
  const sharedGoals = overlapLabels(myGoals, candidate?.goals)
  const sharedLangs = overlapLabels(lcSet(me?.languages), candidate?.languages)

  // Complementary goal pairing — the highest-value match (one mentors, one seeks)
  const mentorMatch =
    (myGoals.has('find a mentor') && candGoals.has('mentor others')) ||
    (myGoals.has('mentor others') && candGoals.has('find a mentor'))
  const iSeekMentor = myGoals.has('find a mentor') && candGoals.has('mentor others')

  const bothInternational = me?.is_international === true && candidate?.is_international === true

  const sameCity =
    profileText(me?.location_city) &&
    profileText(candidate?.location_city) &&
    normaliseDiscoverText(me.location_city) === normaliseDiscoverText(candidate.location_city)

  const sameUniversity =
    profileText(me?.university) &&
    profileText(candidate?.university) &&
    normaliseDiscoverText(me.university) === normaliseDiscoverText(candidate.university)

  const samePersona = profileText(me?.persona) && me?.persona === candidate?.persona
  const profileSignal = discoverProfileSignal(candidate, candidateSkills)

  let score = 0
  score += Math.min(sharedInterests.length, 4) * 4
  if (mentorMatch) score += 8
  score += Math.min(sharedGoals.length, 3) * 2
  if (bothInternational) score += 3
  score += Math.min(sharedLangs.length, 2) * 1.5
  if (samePersona) score += 1
  if (sameUniversity) score += 4
  if (sameCity) score += 2
  score += Math.min(sharedSkills.length, 4) * 2
  score += Math.min(mutualCount, 5) * 2
  if (profileSignal >= 70) score += 1

  const tags: string[] = []
  if (sharedInterests.length) tags.push(...sharedInterests.slice(0, 2))
  if (bothInternational) tags.push('New to Munich')
  if (sharedLangs.length) tags.push(sharedLangs[0])
  if (sameUniversity && candidate.university) tags.push(candidate.university)
  if (mutualCount > 0) tags.push(`${mutualCount} mutual`)
  if (sharedSkills.length) tags.push(sharedSkills[0])

  let reason = 'Worth getting to know.'
  if (iSeekMentor) {
    reason = `Open to mentoring${sharedInterests.length ? ` — also into ${sharedInterests[0]}` : ''}.`
  } else if (mentorMatch) {
    reason = 'Looking for a mentor like you.'
  } else if (sharedInterests.length >= 2) {
    reason = `Both into ${sharedInterests.slice(0, 2).join(' and ')}.`
  } else if (sharedInterests.length === 1 && bothInternational) {
    reason = `Also new to Munich and into ${sharedInterests[0]}.`
  } else if (sharedInterests.length === 1) {
    reason = `Also into ${sharedInterests[0]}.`
  } else if (bothInternational) {
    reason = `Also new to Munich${candidate.home_country ? ` (from ${candidate.home_country})` : ''}.`
  } else if (sharedGoals.length) {
    reason = `Shares your goal: ${sharedGoals[0].toLowerCase()}.`
  } else if (sharedLangs.length) {
    reason = `Also speaks ${sharedLangs[0]}.`
  } else if (sameUniversity) {
    reason = `Also at ${candidate.university}.`
  } else if (sharedSkills.length) {
    reason = `Shares ${sharedSkills[0]} with you.`
  } else if (mutualCount > 0) {
    reason = `${mutualCount} mutual connection${mutualCount === 1 ? '' : 's'} in your knot.`
  } else if (sameCity) {
    reason = `Also based in ${candidate.location_city}.`
  }

  return {
    match_reason: reason,
    match_reasons: [...new Set(tags)].slice(0, 4),
    match_score: score,
    profile_signal: profileSignal,
  }
}

usersRouter.get('/search', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })

  try {
    const parsedQuery = searchUsersQuerySchema.safeParse(req.query)
    if (!parsedQuery.success) {
      return res.status(422).json({ error: 'Invalid query params', fields: parsedQuery.error.flatten() })
    }

    const { q, skill } = parsedQuery.data

    const meResult = await supabase
      .from('users')
      .select('id, full_name, username, headline, bio, location_city, university, current_company, status')
      .eq('id', req.appUserId)
      .maybeSingle()

    if (meResult.error) return res.status(500).json({ error: meResult.error.message })

    let usersQuery = supabase
      .from('users')
      .select('id, full_name, username, avatar_url, headline, bio, location_city, university, current_company, status, created_at')
      .neq('id', req.appUserId)
      .order('created_at', { ascending: false })
      .limit(50)

    if (q) {
      const escaped = q.replace(/[,()]/g, ' ').trim()
      if (escaped.length > 0) {
        usersQuery = usersQuery.or(
          `full_name.ilike.%${escaped}%,username.ilike.%${escaped}%,headline.ilike.%${escaped}%,location_city.ilike.%${escaped}%,university.ilike.%${escaped}%,current_company.ilike.%${escaped}%`
        )
      }
    }

    const usersResult = await usersQuery
    if (usersResult.error) return res.status(500).json({ error: usersResult.error.message })

    let users = usersResult.data ?? []

    if (skill) {
      const catalogResult = await supabase
        .from('skill_catalog')
        .select('id')
        .ilike('name', `%${skill}%`)

      if (catalogResult.error) return res.status(500).json({ error: catalogResult.error.message })

      const skillIds = (catalogResult.data ?? []).map((s) => s.id)

      if (skillIds.length) {
        const userSkillsResult = await supabase.from('user_skills').select('user_id').in('skill_id', skillIds)
        if (userSkillsResult.error) return res.status(500).json({ error: userSkillsResult.error.message })

        const ids = new Set((userSkillsResult.data ?? []).map((s) => s.user_id))
        users = users.filter((u) => ids.has(u.id))
      } else {
        users = []
      }
    }

    const userIds = users.map((u) => u.id)
    const skillsByUser = await skillsForUsers(userIds)
    const mySkillsByUser = await skillsForUsers([req.appUserId])
    const mySkills = mySkillsByUser.get(req.appUserId) ?? []

    const enriched = users.map((u) => {
      const skills = skillsByUser.get(u.id) ?? []
      return {
        ...u,
        skills,
        mutual_connections_count: 0,
        ...discoverReasonFor(meResult.data, mySkills, u, skills, 0),
      }
    })

    return res.json({ users: enriched })
  } catch (err) {
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Failed to search users' })
  }
})

usersRouter.get('/panel/:id', requireAuth, async (req, res) => {
  try {
    const params = userPanelParamSchema.safeParse(req.params)
    if (!params.success) {
      return res.status(422).json({ error: 'Invalid user id', fields: params.error.flatten() })
    }
    const userId = params.data.id

    const userResult = await supabase
      .from('users')
      .select('id, full_name, username, avatar_url, bio, headline, location_city, status, university, current_company, referral_score, contact_email, linkedin_url, website_url, github_url, languages')
      .eq('id', userId)
      .maybeSingle()

    if (userResult.error) return res.status(500).json({ error: userResult.error.message })
    if (!userResult.data) return res.status(404).json({ error: 'User not found' })

    // All extended queries use allSettled: failures return empty data and never hang.
    const [skillsR, recentPostsR, eduR, expR, updatesR, referralsCountR] = await Promise.allSettled([
      supabase.from('user_skills').select('skill_id, skill_catalog(id, name, category)').eq('user_id', userId).limit(8),
      supabase.from('posts').select('id, title, body, image_url, channel_id, created_at, upvote_count, comment_count').eq('author_id', userId).order('created_at', { ascending: false }).limit(3),
      supabase.from('user_education').select('id, institution, degree, field, start_year, end_year, description').eq('user_id', userId).order('sort_order').limit(6),
      supabase.from('user_experience').select('id, company, role, start_date, end_date, description').eq('user_id', userId).order('sort_order').limit(6),
      supabase.from('updates').select('id, content, created_at').eq('user_id', userId).order('created_at', { ascending: false }).limit(1),
      supabase.from('referrals').select('id', { count: 'exact', head: true }).eq('referrer_id', userId).eq('status', 'submitted').eq('hr_flagged', false),
    ])

    const skillsData = (skillsR.status === 'fulfilled' && !skillsR.value.error)
      ? (skillsR.value.data ?? []).map((row: any) => ({
          id: row.skill_id,
          name: row.skill_catalog?.name ?? '',
          category: row.skill_catalog?.category ?? '',
          is_verified: true,
        }))
      : []

    const postsRaw = (recentPostsR.status === 'fulfilled' && !recentPostsR.value.error) ? (recentPostsR.value.data ?? []) : []
    const channelIds = [...new Set(postsRaw.map((p: any) => p.channel_id).filter(Boolean) as string[])]
    const channelsMap = new Map<string, { slug: string; name: string }>()
    if (channelIds.length) {
      const ch = await supabase.from('channels').select('id, slug, name').in('id', channelIds)
      for (const c of (ch.data ?? [])) channelsMap.set(c.id, c)
    }
    const recentPosts = postsRaw.map((p: any) => ({ ...p, channel: p.channel_id ? channelsMap.get(p.channel_id) ?? null : null }))

    return res.json({
      user: userResult.data,
      skills: skillsData,
      education: (eduR.status === 'fulfilled' && !eduR.value.error) ? (eduR.value.data ?? []) : [],
      experience: (expR.status === 'fulfilled' && !expR.value.error) ? (expR.value.data ?? []) : [],
      recentPosts,
      latestPost: recentPosts[0] ?? null,
      latestUpdate: (updatesR.status === 'fulfilled' && !updatesR.value.error) ? (updatesR.value.data?.[0] ?? null) : null,
      submittedReferralCount: (referralsCountR.status === 'fulfilled' && !referralsCountR.value.error) ? (referralsCountR.value.count ?? 0) : 0,
    })
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('panel/:id unexpected error:', err)
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Unknown error' })
  }
})

// Skill catalog (public)
usersRouter.get('/skills/catalog', async (_req, res) => {
  const result = await supabase.from('skill_catalog').select('id, name, category').order('category').order('name')
  if (result.error) return res.status(500).json({ error: result.error.message })
  return res.json({ catalog: result.data ?? [] })
})

// Extended profile (education, experience, skills, languages)
usersRouter.get('/me/profile-extended', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })
  try {
    const [eduR, expR, skillsR, userR] = await Promise.allSettled([
      supabase.from('user_education').select('*').eq('user_id', req.appUserId).order('sort_order'),
      supabase.from('user_experience').select('*').eq('user_id', req.appUserId).order('sort_order'),
      supabase.from('user_skills').select('skill_id, source, skill_catalog(id, name, category)').eq('user_id', req.appUserId),
      supabase.from('users').select('languages').eq('id', req.appUserId).maybeSingle(),
    ])
    return res.json({
      education: (eduR.status === 'fulfilled' && !eduR.value.error) ? (eduR.value.data ?? []) : [],
      experience: (expR.status === 'fulfilled' && !expR.value.error) ? (expR.value.data ?? []) : [],
      skills: (skillsR.status === 'fulfilled' && !skillsR.value.error)
        ? (skillsR.value.data ?? []).map((row: any) => ({ skill_id: row.skill_id, source: row.source, ...row.skill_catalog }))
        : [],
      languages: (userR.status === 'fulfilled' && !userR.value.error) ? (userR.value.data?.languages ?? []) : [],
    })
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('profile-extended error:', err)
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Failed to load extended profile' })
  }
})

// Save education entries (full replace)
usersRouter.put('/me/education', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })
  const items: Array<{ institution: string; degree?: string; field?: string; start_year?: number; end_year?: number; description?: string }> = req.body.items ?? req.body.education ?? []
  await supabase.from('user_education').delete().eq('user_id', req.appUserId)
  if (items.length > 0) {
    const rows = items.map((item, idx) => {
      const sy = item.start_year != null ? Number(String(item.start_year).slice(0, 4)) : null
      const ey = item.end_year != null ? Number(String(item.end_year).slice(0, 4)) : null
      return {
        user_id: req.appUserId!,
        institution: item.institution,
        degree: item.degree ?? null,
        field: item.field ?? null,
        start_year: sy && !isNaN(sy) ? sy : null,
        end_year: ey && !isNaN(ey) ? ey : null,
        description: item.description ?? null,
        sort_order: idx,
      }
    })
    const insert = await supabase.from('user_education').insert(rows).select('*')
    if (insert.error) return res.status(500).json({ error: insert.error.message })
    return res.json({ education: insert.data })
  }
  return res.json({ education: [] })
})

// Save experience entries (full replace)
usersRouter.put('/me/experience', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })
  const items: Array<{ company: string; role: string; start_date?: string; end_date?: string; description?: string }> = req.body.items ?? req.body.experience ?? []
  await supabase.from('user_experience').delete().eq('user_id', req.appUserId)
  if (items.length > 0) {
    function toFullDate(d?: string): string | null {
      if (!d || d === 'present') return d === 'present' ? null : null
      const trimmed = d.trim()
      if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) return trimmed
      if (/^\d{4}-\d{2}$/.test(trimmed)) return `${trimmed}-01`
      if (/^\d{4}$/.test(trimmed)) return `${trimmed}-01-01`
      return null
    }
    const rows = items.map((item, idx) => ({
      user_id: req.appUserId!,
      company: item.company,
      role: item.role,
      start_date: toFullDate(item.start_date),
      end_date: item.end_date === 'present' ? null : toFullDate(item.end_date),
      description: item.description ?? null,
      sort_order: idx,
    }))
    const insert = await supabase.from('user_experience').insert(rows).select('*')
    if (insert.error) return res.status(500).json({ error: insert.error.message })
    return res.json({ experience: insert.data })
  }
  return res.json({ experience: [] })
})

// Save skills (full replace)
usersRouter.put('/me/skills', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })
  const skillIds: number[] = (req.body.skillIds ?? []).map(Number).filter(Boolean)
  await supabase.from('user_skills').delete().eq('user_id', req.appUserId)
  if (skillIds.length > 0) {
    const rows = skillIds.map((id) => ({ user_id: req.appUserId!, skill_id: id, source: 'manual' }))
    const insert = await supabase.from('user_skills').insert(rows)
    if (insert.error) return res.status(500).json({ error: insert.error.message })
  }
  const updated = await supabase.from('user_skills').select('skill_id, source, skill_catalog(id, name, category)').eq('user_id', req.appUserId)
  const skills = (updated.data ?? []).map((row: any) => ({ skill_id: row.skill_id, source: row.source, ...row.skill_catalog }))
  return res.json({ skills })
})

// Local CV extraction
// Accepts JSON body: { pdfBase64?: string, text?: string, filename?: string }
// (Avoids multipart/form-data which has issues with @vercel/node serverless.)
usersRouter.post('/me/cv-extract', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })

  const { pdfBase64, text: directText, filename } = (req.body ?? {}) as { pdfBase64?: string; text?: string; filename?: string }

  let text = ''
  try {
    if (typeof directText === 'string' && directText.trim().length > 0) {
      text = directText
    } else if (typeof pdfBase64 === 'string' && pdfBase64.length > 0) {
      const buf = Buffer.from(pdfBase64.replace(/^data:application\/pdf;base64,/, ''), 'base64')
      if (buf.length > 12 * 1024 * 1024) {
        return res.status(413).json({ error: 'File too large (max 12 MB)' })
      }
      try {
        const pdfParse = (await import('pdf-parse')).default
        const parsed = await pdfParse(buf)
        text = parsed.text
      } catch {
        text = buf.toString('utf-8')
      }
    } else {
      return res.status(422).json({ error: 'Provide either pdfBase64 or text' })
    }
  } catch (e) {
    return res.status(422).json({ error: e instanceof Error ? e.message : 'Could not parse file' })
  }

  if (!text.trim()) return res.status(422).json({ error: 'Could not extract text from file' })
  // filename is unused but accepted for client compatibility
  void filename

  try {
    const analysis = await analyseCv(text)
    const parsed = {
      headline: analysis.profileExtract.headline,
      bio: analysis.profileExtract.bio,
      education: analysis.profileExtract.education,
      experience: analysis.profileExtract.experience,
      skills: analysis.extractedSkills
        .filter((skill) => skill.category !== 'language')
        .map((skill) => skill.name),
      languages: analysis.extractedSkills
        .filter((skill) => skill.category === 'language')
        .map((skill) => skill.name),
    }

    // Map skill names to skill_catalog IDs (case-insensitive)
    const skillNames: string[] = Array.isArray(parsed.skills) ? parsed.skills.filter((s: unknown) => typeof s === 'string') : []
    let skillIds: number[] = []
    if (skillNames.length) {
      const allCat = await supabase.from('skill_catalog').select('id, name')
      const byLower = new Map<string, number>()
      for (const row of (allCat.data ?? []) as Array<{ id: number; name: string }>) {
        byLower.set(row.name.toLowerCase(), row.id)
      }
      const matched = new Set<number>()
      for (const name of skillNames) {
        const key = name.toLowerCase().trim()
        if (byLower.has(key)) matched.add(byLower.get(key)!)
        // Try partial matches, for example React.js to React.
        else {
          for (const [catName, catId] of byLower) {
            if (key.includes(catName) || catName.includes(key)) { matched.add(catId); break }
          }
        }
      }
      skillIds = [...matched]
    }

    // Normalize education / experience shape
    const education = Array.isArray(parsed.education) ? parsed.education.map((e: any) => ({
      institution: String(e.institution ?? ''),
      degree: String(e.degree ?? ''),
      field: String(e.field ?? ''),
      start_year: e.start_year ? String(e.start_year) : '',
      end_year: e.end_year ? String(e.end_year) : '',
      description: String(e.description ?? ''),
    })) : []
    const experience = Array.isArray(parsed.experience) ? parsed.experience.map((e: any) => ({
      company: String(e.company ?? ''),
      role: String(e.role ?? ''),
      start_date: e.start_date ? String(e.start_date) : '',
      end_date: e.end_date ? String(e.end_date) : '',
      description: String(e.description ?? ''),
    })) : []

    const extracted = {
      headline: typeof parsed.headline === 'string' ? parsed.headline.slice(0, 120) : null,
      bio: typeof parsed.bio === 'string' ? parsed.bio.slice(0, 500) : null,
      education,
      experience,
      skillIds,
      skillNames, // for display in diff preview
      languages: Array.isArray(parsed.languages) ? parsed.languages.filter((l: unknown) => typeof l === 'string') : [],
    }
    return res.json({ extracted })
  } catch (err) {
    return res.status(500).json({ error: err instanceof Error ? err.message : 'CV extraction failed' })
  }
})

// People you may know suggestions
usersRouter.get('/suggestions', requireAuth, async (req, res) => {
  if (!req.appUserId) return res.status(404).json({ error: 'Profile not found' })

  try {
    const connections = await supabase
      .from('connections')
      .select('requester_id, addressee_id, status')
      .or(`requester_id.eq.${req.appUserId},addressee_id.eq.${req.appUserId}`)

    if (connections.error) return res.status(500).json({ error: connections.error.message })

    const excludeIds = new Set<string>([req.appUserId])
    const myAcceptedIds: string[] = []

    for (const c of connections.data ?? []) {
      excludeIds.add(c.requester_id)
      excludeIds.add(c.addressee_id)

      if (c.status === 'accepted') {
        const peerId = c.requester_id === req.appUserId ? c.addressee_id : c.requester_id
        myAcceptedIds.push(peerId)
      }
    }

    const myUser = await supabase
      .from('users')
      .select('id, full_name, username, headline, bio, location_city, university, current_company, status, persona, interests, goals, is_international, home_country, munich_tenure, languages')
      .eq('id', req.appUserId)
      .maybeSingle()

    if (myUser.error) return res.status(500).json({ error: myUser.error.message })

    const excluded = [...excludeIds]
    const candidatesQuery = await supabase
      .from('users')
      .select('id, full_name, username, avatar_url, headline, bio, location_city, university, current_company, status, persona, interests, goals, is_international, home_country, munich_tenure, languages, created_at')
      .not('id', 'in', `(${excluded.join(',')})`)
      .order('created_at', { ascending: false })
      .limit(80)

    if (candidatesQuery.error) return res.status(500).json({ error: candidatesQuery.error.message })

    const candidates = candidatesQuery.data ?? []
    const candidateIds = candidates.map((u) => u.id)
    const candidateIdSet = new Set(candidateIds)

    const [skillsByUser, mySkillsByUser] = await Promise.all([
      skillsForUsers(candidateIds),
      skillsForUsers([req.appUserId]),
    ])

    const mutualsByCandidate = new Map<string, number>()
    const myAcceptedSet = new Set(myAcceptedIds)

    if (candidateIds.length > 0 && myAcceptedIds.length > 0) {
      const [a, b] = await Promise.all([
        supabase
          .from('connections')
          .select('requester_id, addressee_id, status')
          .in('requester_id', candidateIds)
          .eq('status', 'accepted'),
        supabase
          .from('connections')
          .select('requester_id, addressee_id, status')
          .in('addressee_id', candidateIds)
          .eq('status', 'accepted'),
      ])

      if (a.error) return res.status(500).json({ error: a.error.message })
      if (b.error) return res.status(500).json({ error: b.error.message })

      for (const row of [...(a.data ?? []), ...(b.data ?? [])]) {
        const candidateId = candidateIdSet.has(row.requester_id)
          ? row.requester_id
          : candidateIdSet.has(row.addressee_id)
            ? row.addressee_id
            : null

        if (!candidateId) continue

        const peerId = row.requester_id === candidateId ? row.addressee_id : row.requester_id
        if (!myAcceptedSet.has(peerId)) continue

        mutualsByCandidate.set(candidateId, (mutualsByCandidate.get(candidateId) ?? 0) + 1)
      }
    }

    const mySkills = mySkillsByUser.get(req.appUserId) ?? []

    const enriched = candidates.map((u) => {
      const skills = skillsByUser.get(u.id) ?? []
      const mutual = mutualsByCandidate.get(u.id) ?? 0

      return {
        ...u,
        skills,
        mutual_connections_count: mutual,
        ...discoverReasonFor(myUser.data, mySkills, u, skills, mutual),
      }
    })

    const sorted = enriched
      .sort((a, b) => {
        const scoreDelta = (b.match_score ?? 0) - (a.match_score ?? 0)
        if (scoreDelta !== 0) return scoreDelta
        return new Date(b.created_at ?? 0).getTime() - new Date(a.created_at ?? 0).getTime()
      })
      .slice(0, 24)

    return res.json({ suggestions: sorted })
  } catch (err) {
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Failed to load suggestions' })
  }
})

usersRouter.get('/public/:id', requireAuth, async (req, res) => {
  try {
    const userId = req.params.id
    if (!userId) return res.status(422).json({ error: 'Invalid user id' })

    // Fetch user core first; fail fast if not found.
    const user = await supabase
      .from('users')
      .select('id, full_name, username, avatar_url, bio, headline, location_city, university, current_company, linkedin_url, website_url, github_url, languages, status, created_at')
      .eq('id', userId)
      .maybeSingle()

    if (user.error) {
      // eslint-disable-next-line no-console
      console.error('public/:id user query error:', user.error)
      return res.status(500).json({ error: user.error.message })
    }
    if (!user.data) return res.status(404).json({ error: 'User not found' })

    // Fetch extended data with individual error handling; return empty arrays on failure.
    // (so a missing table from an unrun migration doesn't break the whole endpoint)
    const [eduResult, expResult, skillsResult] = await Promise.allSettled([
      supabase.from('user_education').select('*').eq('user_id', userId).order('sort_order'),
      supabase.from('user_experience').select('*').eq('user_id', userId).order('sort_order'),
      supabase.from('user_skills').select('skill_id, skill_catalog(id, name, category)').eq('user_id', userId),
    ])

    const education = (eduResult.status === 'fulfilled' && !eduResult.value.error) ? (eduResult.value.data ?? []) : []
    const experience = (expResult.status === 'fulfilled' && !expResult.value.error) ? (expResult.value.data ?? []) : []
    const skills = (skillsResult.status === 'fulfilled' && !skillsResult.value.error)
      ? (skillsResult.value.data ?? []).map((row: any) => ({ skill_id: row.skill_id, ...row.skill_catalog }))
      : []

    return res.json({ user: user.data, education, experience, skills })
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('public/:id unexpected error:', err)
    return res.status(500).json({ error: err instanceof Error ? err.message : 'Unknown error' })
  }
})

usersRouter.get('/:username', requireAuth, async (req, res) => {
  const params = usernameParamSchema.safeParse(req.params)
  if (!params.success) {
    return res.status(422).json({ error: 'Invalid username', fields: params.error.flatten() })
  }
  const username = params.data.username
  const result = await supabase
    .from('users')
    .select('id, full_name, username, avatar_url, bio, location_city, status, university, current_company, referral_score')
    .eq('username', username)
    .maybeSingle()

  if (result.error) {
    return res.status(500).json({ error: result.error.message })
  }
  if (!result.data) {
    return res.status(404).json({ error: 'User not found' })
  }

  return res.json({ user: result.data })
})
